### ISSUE TITLE
Run vanguard and ground station unit tests in Travis CI

### ISSUE THREAD

**Issue by marshall** [openkosmosorg/vanguard#8]
We need to integrate with [Travis CI](https://travis-ci.org/openkosmosorg/vanguard) by creating a top level `.travis.yml` that tells Travis how to run our various unit tests whenever we open a new pull request.. to make sure we aren't creating regressions.

@kyleparrott want to take a look?

**Comment by kyleparrott** [comment]
Sure thing.
